# Generated by Django 4.2 on 2023-04-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('employ_code', models.IntegerField()),
                ('designation', models.CharField(max_length=200)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('basic_pay', models.IntegerField()),
                ('grade_pay', models.IntegerField()),
                ('d_a', models.IntegerField()),
                ('house_rent', models.IntegerField()),
                ('washing_allowance', models.IntegerField()),
                ('conveyance_allowance', models.IntegerField()),
                ('gross_salary', models.IntegerField()),
                ('n_p_s', models.IntegerField()),
                ('g_i_s', models.IntegerField()),
                ('l_i_c', models.IntegerField()),
                ('house_rent_d', models.IntegerField()),
                ('income_tax', models.IntegerField()),
                ('professional_tax', models.IntegerField()),
                ('total_deduction', models.IntegerField()),
                ('net_payable', models.IntegerField()),
            ],
            options={
                'ordering': ['-year', '-month', '-name'],
            },
        ),
    ]
