# Generated by Django 4.2 on 2023-05-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_files_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
