# Generated by Django 4.2 on 2023-05-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_files_is_converted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employ_code', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('pay_scale', models.IntegerField()),
                ('designation', models.CharField(max_length=200)),
                ('no_of_days', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('basic_pay', models.IntegerField()),
                ('da_34', models.IntegerField()),
                ('Npa', models.IntegerField()),
                ('da_203', models.IntegerField()),
                ('aca', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('mta', models.IntegerField()),
                ('nps_14', models.IntegerField()),
                ('adj_amt_1', models.IntegerField()),
                ('gross_salary', models.IntegerField()),
                ('total_deduction', models.IntegerField()),
                ('net_payable', models.IntegerField()),
                ('n_p_s_10', models.IntegerField()),
                ('n_p_s_14', models.IntegerField()),
                ('n_p_s', models.IntegerField()),
                ('IT', models.IntegerField()),
                ('PT', models.IntegerField()),
                ('HR', models.IntegerField()),
                ('HR_rec', models.IntegerField()),
                ('adj_amt_2', models.IntegerField()),
                ('other', models.IntegerField()),
                ('net_deduction', models.IntegerField()),
            ],
            options={
                'ordering': ['-year', '-month', '-name'],
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
