# Generated by Django 3.0.5 on 2023-05-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_entries_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='employ_code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='entries',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
